/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellGuideRouteImport } from './routes/_shell/guide'
import { Route as ShellListsIndexRouteImport } from './routes/_shell/lists.index'
import { Route as ShellListsApplyRouteImport } from './routes/_shell/lists/apply'
import { Route as ShellListsBlacklistRouteImport } from './routes/_shell/lists/blacklist'
import { Route as ShellListsKeywordsRouteImport } from './routes/_shell/lists/keywords'
import { Route as ShellListsRankedRouteImport } from './routes/_shell/lists/ranked'
import { Route as ShellListsRescueRouteImport } from './routes/_shell/lists/rescue'
import { Route as ShellListsWhitelistRouteImport } from './routes/_shell/lists/whitelist'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGuideRoute = ShellGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => ShellRoute,
} as any)
const ShellListsIndexRoute = ShellListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellListsApplyRoute = ShellListsApplyRouteImport.update({
  id: '/lists/apply',
  path: '/lists/apply',
  getParentRoute: () => ShellRoute,
} as any)
const ShellListsBlacklistRoute = ShellListsBlacklistRouteImport.update({
  id: '/lists/blacklist',
  path: '/lists/blacklist',
  getParentRoute: () => ShellRoute,
} as any)
const ShellListsKeywordsRoute = ShellListsKeywordsRouteImport.update({
  id: '/lists/keywords',
  path: '/lists/keywords',
  getParentRoute: () => ShellRoute,
} as any)
const ShellListsRankedRoute = ShellListsRankedRouteImport.update({
  id: '/lists/ranked',
  path: '/lists/ranked',
  getParentRoute: () => ShellRoute,
} as any)
const ShellListsRescueRoute = ShellListsRescueRouteImport.update({
  id: '/lists/rescue',
  path: '/lists/rescue',
  getParentRoute: () => ShellRoute,
} as any)
const ShellListsWhitelistRoute = ShellListsWhitelistRouteImport.update({
  id: '/lists/whitelist',
  path: '/lists/whitelist',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/guide': typeof ShellGuideRoute
  '/lists/apply': typeof ShellListsApplyRoute
  '/lists/blacklist': typeof ShellListsBlacklistRoute
  '/lists/keywords': typeof ShellListsKeywordsRoute
  '/lists/ranked': typeof ShellListsRankedRoute
  '/lists/rescue': typeof ShellListsRescueRoute
  '/lists/whitelist': typeof ShellListsWhitelistRoute
  '/lists/': typeof ShellListsIndexRoute
}
export interface FileRoutesByTo {
  '/guide': typeof ShellGuideRoute
  '/': typeof ShellIndexRoute
  '/lists/apply': typeof ShellListsApplyRoute
  '/lists/blacklist': typeof ShellListsBlacklistRoute
  '/lists/keywords': typeof ShellListsKeywordsRoute
  '/lists/ranked': typeof ShellListsRankedRoute
  '/lists/rescue': typeof ShellListsRescueRoute
  '/lists/whitelist': typeof ShellListsWhitelistRoute
  '/lists': typeof ShellListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/guide': typeof ShellGuideRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/lists/apply': typeof ShellListsApplyRoute
  '/_shell/lists/blacklist': typeof ShellListsBlacklistRoute
  '/_shell/lists/keywords': typeof ShellListsKeywordsRoute
  '/_shell/lists/ranked': typeof ShellListsRankedRoute
  '/_shell/lists/rescue': typeof ShellListsRescueRoute
  '/_shell/lists/whitelist': typeof ShellListsWhitelistRoute
  '/_shell/lists/': typeof ShellListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/lists/apply'
    | '/lists/blacklist'
    | '/lists/keywords'
    | '/lists/ranked'
    | '/lists/rescue'
    | '/lists/whitelist'
    | '/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/guide'
    | '/'
    | '/lists/apply'
    | '/lists/blacklist'
    | '/lists/keywords'
    | '/lists/ranked'
    | '/lists/rescue'
    | '/lists/whitelist'
    | '/lists'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/guide'
    | '/_shell/'
    | '/_shell/lists/apply'
    | '/_shell/lists/blacklist'
    | '/_shell/lists/keywords'
    | '/_shell/lists/ranked'
    | '/_shell/lists/rescue'
    | '/_shell/lists/whitelist'
    | '/_shell/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/guide': {
      id: '/_shell/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof ShellGuideRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lists/': {
      id: '/_shell/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ShellListsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lists/apply': {
      id: '/_shell/lists/apply'
      path: '/lists/apply'
      fullPath: '/lists/apply'
      preLoaderRoute: typeof ShellListsApplyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lists/blacklist': {
      id: '/_shell/lists/blacklist'
      path: '/lists/blacklist'
      fullPath: '/lists/blacklist'
      preLoaderRoute: typeof ShellListsBlacklistRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lists/keywords': {
      id: '/_shell/lists/keywords'
      path: '/lists/keywords'
      fullPath: '/lists/keywords'
      preLoaderRoute: typeof ShellListsKeywordsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lists/ranked': {
      id: '/_shell/lists/ranked'
      path: '/lists/ranked'
      fullPath: '/lists/ranked'
      preLoaderRoute: typeof ShellListsRankedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lists/rescue': {
      id: '/_shell/lists/rescue'
      path: '/lists/rescue'
      fullPath: '/lists/rescue'
      preLoaderRoute: typeof ShellListsRescueRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lists/whitelist': {
      id: '/_shell/lists/whitelist'
      path: '/lists/whitelist'
      fullPath: '/lists/whitelist'
      preLoaderRoute: typeof ShellListsWhitelistRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellGuideRoute: typeof ShellGuideRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellListsApplyRoute: typeof ShellListsApplyRoute
  ShellListsBlacklistRoute: typeof ShellListsBlacklistRoute
  ShellListsKeywordsRoute: typeof ShellListsKeywordsRoute
  ShellListsRankedRoute: typeof ShellListsRankedRoute
  ShellListsRescueRoute: typeof ShellListsRescueRoute
  ShellListsWhitelistRoute: typeof ShellListsWhitelistRoute
  ShellListsIndexRoute: typeof ShellListsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellGuideRoute: ShellGuideRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellListsApplyRoute: ShellListsApplyRoute,
  ShellListsBlacklistRoute: ShellListsBlacklistRoute,
  ShellListsKeywordsRoute: ShellListsKeywordsRoute,
  ShellListsRankedRoute: ShellListsRankedRoute,
  ShellListsRescueRoute: ShellListsRescueRoute,
  ShellListsWhitelistRoute: ShellListsWhitelistRoute,
  ShellListsIndexRoute: ShellListsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
